name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  PATCH_VERSION: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/zaval/kio-s3:main

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DAWSSDK_DIR=/home/neon/aws-sdk/lib/cmake/AWSSDK -DCMAKE_PREFIX_PATH=/home/neon/aws-sdk -DENABLE_TESTING=1

    - name: Build & Test
      env:
        PATCH_VERSION: ${{ github.run_id }}
      run: |
        git config --global --add safe.directory /__w/kio-s3/kio-s3
        cmake --build build --config ${{env.BUILD_TYPE}} -- -j$(nproc)
        cd build
        ctest

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: CMake Tests
        path: build/reports/*.xml
        reporter: java-junit

#    - name: CPack
#      run: |
#        cd build
#        cpack
#        cp kio-s3-1.0.${{ github.run_id }}-Linux.deb ../kio-s3-1.0.${{ github.run_id }}-Linux.deb
#
#    - name: Upload artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: S3-KIO
#        path: ./kio-s3-1.0.${{ github.run_id }}-Linux.deb
